### ISSUE TITLE
Build time sorted by spended time

### ISSUE THREAD

**Issue by stokito** [timgifford/maven-buildtime-extension#18]
Could you add some ability to sort desceding goals by spended time?
I have a very big project and want to see most problematic items but now i need to expost data to CSV and then sort them in Excel.
For me looks that this feature will be useful.

**Comment by leonard84** [comment]
That's exactly the reason we added CSV support so that you could analyse it in Excel or whatever other Spreadsheet program you are using. The console is the wrong place to analyse data as there are many different dimensions you might want to analyse, e.g. which module took the longest, or aggregate the time for each mojo in the different modules.

**Comment by stokito** [comment]
Ok, thanks. Maybe you can determine the most used way and add it? I mean for me sorting by speed looks like first interesting metric.

**Comment by timgifford** [comment]
@stokito this extensions original primary concern was capturing the data and reporting it out in the console. In the next major release (3.0) we will decouple capturing from reporting. This will allow you to output the data to csv or some other location so you can sort, aggregate, and filter however you'd like.

Until then, you can work around using @leonard84 suggestion.
