### ISSUE TITLE
Change -Dbuildtime.output.csv.file default value

### ISSUE THREAD

**Issue by alessandro-violante-dsgroup** [timgifford/maven-buildtime-extension#49]
Hi,

I've noticed that, when using the -Dbuildtime.output.csv.file property, regardless of the value I put there, the plugin always searches for a "target" directory at the beginning of the path.

For example, if I use the following value:

-Dbuildtime.output.csv.file=dir/output.csv

The plugin will try to write the .csv file in the directory "target/dir/output.csv".

The "target" directory, in my example, doesn't exist, so that the export fails.

Could I omit or override in any way that "target" default value, as my "target" folder is in another directory?

Thanks a lot for your support.

Alessandro

**Comment by timgifford** [comment]
Placing the report in the /target directory is by design. The target directory should be created at early phases of the maven lifecycle. 
Did you configure a different target directory in Maven? 

It looks like we [hard coded the target directory](https://github.com/timgifford/maven-buildtime-extension/blob/master/src/main/java/co/leantechniques/maven/buildtime/output/CsvReporter.java#L26), which isn't ideal
